version: '3.3'

services:
   db:
      image: mysql:5.7
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=wh
        - MYSQL_PASSWORD=wh

volumes:
    db_data: